CFLAGS += -DBOARD_LAUNCHPAD=1

CONTIKI_TARGET_DIRS += eve003 common

BOARD_SOURCEFILES += board.c launchpad-sensors.c leds-arch.c button-sensor.c 
BOARD_SOURCEFILES += ext-flash.c board-spi.c

### for your another sensor driver
###BOARD_SOURCEFILES += adcin-sensor.c
BOARD_SOURCEFILES += led_sensor.c switch-sensor.c

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1
